name: Pull Request

on:
  pull_request:

jobs:
  test:
    name: Test
    uses: "./.github/workflows/tests.yml"
    secrets: inherit

  lint:
    name: Lint
    uses: "./.github/workflows/lint.yml"
    secrets: inherit
